### ISSUE TITLE
Weakness in AES key

### ISSUE THREAD

**Issue by linted** [linted/Skip-Trace#11]
Right now the key we are using is a 32 character space centered key of the hostname of the client. because of this, if an attacker knows the hostname of the client, which is by no means a secret, they would be able to decrypt the return traffic from the server. Right now that is not much of a problem, as we aren't sending anything too important back. However if in the future we decide to send commands back to the client to say take a picture or keep checking in every 5 minuets, this would be a very big problem. 

My proposed solution is to use pycrypto's random number generator to send a key along with the client hello. This way the key will change every check-in and is guaranteed to be random. It should then be nearly impossible for a man-in-the-middle attack where the attacker stops the legit traffic and tries to brute force the AES key, as the client should time out before then and generate a new key.

**Comment by msmith533** [comment]
This sounds like a solid course of action
