### ISSUE TITLE
switch to datetime

### ISSUE THREAD

**Issue by linted** [linted/Skip-Trace#14]
Currently the string that the server creates when logging a client check in is extremely long and slightly hard to read. I propose that we switch to the datetime library and use the strftime() function. This function will allow us to get each part of the date in 2 characters each, while also using formating for things like the client IP. 

If done correctly it should shorten down the line considerably and let us get rid of the ugly global months array.

**Comment by calebmckay** [comment]
Fixed in Pull Request #16, pending review.
