### ISSUE TITLE
Reject invalid hostnames

### ISSUE THREAD

**Issue by linted** [linted/Skip-Trace#18]
RFC 952 and RFC 1123 define some rules for Hostnames. Basically a Hostname can only be alpha numeric, so we can deny any Hostname that has a special character. This is remove any need to escape characters that could be dangerous to future features. try using: `string.isalnum()`

**Comment by calebmckay** [comment]
Unfortunately, `string.isalnum()` is slightly too simplistic, as hyphens (-) are allowed, and periods (.) are allowed to separate pieces (labels) of the host name. Each label can't be more than 63 characters, and the whole hostname also can't be over 253 characters [(Source)](https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames). Perhaps using `import re` and regular expressions would be a better approach. [Here's one method.](http://stackoverflow.com/a/2532344/7196647)
